FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    software-properties-common \
 && add-apt-repository universe \
 && apt-get update \
 && apt-get install -y --no-install-recommends \
    build-essential \
    valgrind \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
VOLUME /workspace

